#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Party_Information")]
public partial class Party_InformationDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertCategory(Category instance);
  partial void UpdateCategory(Category instance);
  partial void DeleteCategory(Category instance);
  partial void InsertClass(Class instance);
  partial void UpdateClass(Class instance);
  partial void DeleteClass(Class instance);
  partial void InsertCollege(College instance);
  partial void UpdateCollege(College instance);
  partial void DeleteCollege(College instance);
  partial void InsertMessage(Message instance);
  partial void UpdateMessage(Message instance);
  partial void DeleteMessage(Message instance);
  partial void InsertPartyStatus(PartyStatus instance);
  partial void UpdatePartyStatus(PartyStatus instance);
  partial void DeletePartyStatus(PartyStatus instance);
  partial void InsertRecord_Details(Record_Details instance);
  partial void UpdateRecord_Details(Record_Details instance);
  partial void DeleteRecord_Details(Record_Details instance);
  partial void InsertUpdate_Data(Update_Data instance);
  partial void UpdateUpdate_Data(Update_Data instance);
  partial void DeleteUpdate_Data(Update_Data instance);
  partial void InsertWork_Info(Work_Info instance);
  partial void UpdateWork_Info(Work_Info instance);
  partial void DeleteWork_Info(Work_Info instance);
  partial void InsertPartyData(PartyData instance);
  partial void UpdatePartyData(PartyData instance);
  partial void DeletePartyData(PartyData instance);
  partial void InsertDatum(Datum instance);
  partial void UpdateDatum(Datum instance);
  partial void DeleteDatum(Datum instance);
  #endregion
	
	public Party_InformationDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Party_InformationConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Party_InformationDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Party_InformationDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Party_InformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Party_InformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Category> Category
	{
		get
		{
			return this.GetTable<Category>();
		}
	}
	
	public System.Data.Linq.Table<Class> Class
	{
		get
		{
			return this.GetTable<Class>();
		}
	}
	
	public System.Data.Linq.Table<College> College
	{
		get
		{
			return this.GetTable<College>();
		}
	}
	
	public System.Data.Linq.Table<Message> Message
	{
		get
		{
			return this.GetTable<Message>();
		}
	}
	
	public System.Data.Linq.Table<PartyStatus> PartyStatus
	{
		get
		{
			return this.GetTable<PartyStatus>();
		}
	}
	
	public System.Data.Linq.Table<Record_Details> Record_Details
	{
		get
		{
			return this.GetTable<Record_Details>();
		}
	}
	
	public System.Data.Linq.Table<Update_Data> Update_Data
	{
		get
		{
			return this.GetTable<Update_Data>();
		}
	}
	
	public System.Data.Linq.Table<Work_Info> Work_Info
	{
		get
		{
			return this.GetTable<Work_Info>();
		}
	}
	
	public System.Data.Linq.Table<PartyData> PartyData
	{
		get
		{
			return this.GetTable<PartyData>();
		}
	}
	
	public System.Data.Linq.Table<Datum> Datum
	{
		get
		{
			return this.GetTable<Datum>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TypeNO;
	
	private string _TypeName;
	
	private System.Nullable<int> _CateforyClassID;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeNOChanging(string value);
    partial void OnTypeNOChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    partial void OnCateforyClassIDChanging(System.Nullable<int> value);
    partial void OnCateforyClassIDChanged();
    #endregion
	
	public Category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNO", DbType="VarChar(50)")]
	public string TypeNO
	{
		get
		{
			return this._TypeNO;
		}
		set
		{
			if ((this._TypeNO != value))
			{
				this.OnTypeNOChanging(value);
				this.SendPropertyChanging();
				this._TypeNO = value;
				this.SendPropertyChanged("TypeNO");
				this.OnTypeNOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="VarChar(50)")]
	public string TypeName
	{
		get
		{
			return this._TypeName;
		}
		set
		{
			if ((this._TypeName != value))
			{
				this.OnTypeNameChanging(value);
				this.SendPropertyChanging();
				this._TypeName = value;
				this.SendPropertyChanged("TypeName");
				this.OnTypeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CateforyClassID", DbType="Int")]
	public System.Nullable<int> CateforyClassID
	{
		get
		{
			return this._CateforyClassID;
		}
		set
		{
			if ((this._CateforyClassID != value))
			{
				this.OnCateforyClassIDChanging(value);
				this.SendPropertyChanging();
				this._CateforyClassID = value;
				this.SendPropertyChanged("CateforyClassID");
				this.OnCateforyClassIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class")]
public partial class Class : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _ClassID;
	
	private string _ClassName;
	
	private System.Nullable<int> _CollegeID;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnCollegeIDChanging(System.Nullable<int> value);
    partial void OnCollegeIDChanged();
    #endregion
	
	public Class()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ClassID
	{
		get
		{
			return this._ClassID;
		}
		set
		{
			if ((this._ClassID != value))
			{
				this.OnClassIDChanging(value);
				this.SendPropertyChanging();
				this._ClassID = value;
				this.SendPropertyChanged("ClassID");
				this.OnClassIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(50)")]
	public string ClassName
	{
		get
		{
			return this._ClassName;
		}
		set
		{
			if ((this._ClassName != value))
			{
				this.OnClassNameChanging(value);
				this.SendPropertyChanging();
				this._ClassName = value;
				this.SendPropertyChanged("ClassName");
				this.OnClassNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeID", DbType="Int")]
	public System.Nullable<int> CollegeID
	{
		get
		{
			return this._CollegeID;
		}
		set
		{
			if ((this._CollegeID != value))
			{
				this.OnCollegeIDChanging(value);
				this.SendPropertyChanging();
				this._CollegeID = value;
				this.SendPropertyChanged("CollegeID");
				this.OnCollegeIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.College")]
public partial class College : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private int _CollegeID;
	
	private string _CollegeName;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCollegeIDChanging(int value);
    partial void OnCollegeIDChanged();
    partial void OnCollegeNameChanging(string value);
    partial void OnCollegeNameChanged();
    #endregion
	
	public College()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CollegeID
	{
		get
		{
			return this._CollegeID;
		}
		set
		{
			if ((this._CollegeID != value))
			{
				this.OnCollegeIDChanging(value);
				this.SendPropertyChanging();
				this._CollegeID = value;
				this.SendPropertyChanged("CollegeID");
				this.OnCollegeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeName", DbType="VarChar(50)")]
	public string CollegeName
	{
		get
		{
			return this._CollegeName;
		}
		set
		{
			if ((this._CollegeName != value))
			{
				this.OnCollegeNameChanging(value);
				this.SendPropertyChanging();
				this._CollegeName = value;
				this.SendPropertyChanged("CollegeName");
				this.OnCollegeNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Message")]
public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StudentNum;
	
	private System.Nullable<int> _TypeClass;
	
	private string _Contents;
	
	private System.Nullable<System.DateTime> _Create_Time;
	
	private string _Message_Status;
	
	private string _Authority;
	
	private System.Nullable<int> _Message_Key;
	
	private System.Nullable<System.DateTime> _Message_Time;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStudentNumChanging(string value);
    partial void OnStudentNumChanged();
    partial void OnTypeClassChanging(System.Nullable<int> value);
    partial void OnTypeClassChanged();
    partial void OnContentsChanging(string value);
    partial void OnContentsChanged();
    partial void OnCreate_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_TimeChanged();
    partial void OnMessage_StatusChanging(string value);
    partial void OnMessage_StatusChanged();
    partial void OnAuthorityChanging(string value);
    partial void OnAuthorityChanged();
    partial void OnMessage_KeyChanging(System.Nullable<int> value);
    partial void OnMessage_KeyChanged();
    partial void OnMessage_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMessage_TimeChanged();
    #endregion
	
	public Message()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNum", DbType="NVarChar(20)")]
	public string StudentNum
	{
		get
		{
			return this._StudentNum;
		}
		set
		{
			if ((this._StudentNum != value))
			{
				this.OnStudentNumChanging(value);
				this.SendPropertyChanging();
				this._StudentNum = value;
				this.SendPropertyChanged("StudentNum");
				this.OnStudentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeClass", DbType="Int")]
	public System.Nullable<int> TypeClass
	{
		get
		{
			return this._TypeClass;
		}
		set
		{
			if ((this._TypeClass != value))
			{
				this.OnTypeClassChanging(value);
				this.SendPropertyChanging();
				this._TypeClass = value;
				this.SendPropertyChanged("TypeClass");
				this.OnTypeClassChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="NVarChar(MAX)")]
	public string Contents
	{
		get
		{
			return this._Contents;
		}
		set
		{
			if ((this._Contents != value))
			{
				this.OnContentsChanging(value);
				this.SendPropertyChanging();
				this._Contents = value;
				this.SendPropertyChanged("Contents");
				this.OnContentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Create_Time
	{
		get
		{
			return this._Create_Time;
		}
		set
		{
			if ((this._Create_Time != value))
			{
				this.OnCreate_TimeChanging(value);
				this.SendPropertyChanging();
				this._Create_Time = value;
				this.SendPropertyChanged("Create_Time");
				this.OnCreate_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_Status", DbType="NChar(10)")]
	public string Message_Status
	{
		get
		{
			return this._Message_Status;
		}
		set
		{
			if ((this._Message_Status != value))
			{
				this.OnMessage_StatusChanging(value);
				this.SendPropertyChanging();
				this._Message_Status = value;
				this.SendPropertyChanged("Message_Status");
				this.OnMessage_StatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authority", DbType="NVarChar(MAX)")]
	public string Authority
	{
		get
		{
			return this._Authority;
		}
		set
		{
			if ((this._Authority != value))
			{
				this.OnAuthorityChanging(value);
				this.SendPropertyChanging();
				this._Authority = value;
				this.SendPropertyChanged("Authority");
				this.OnAuthorityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_Key", DbType="Int")]
	public System.Nullable<int> Message_Key
	{
		get
		{
			return this._Message_Key;
		}
		set
		{
			if ((this._Message_Key != value))
			{
				this.OnMessage_KeyChanging(value);
				this.SendPropertyChanging();
				this._Message_Key = value;
				this.SendPropertyChanged("Message_Key");
				this.OnMessage_KeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Message_Time
	{
		get
		{
			return this._Message_Time;
		}
		set
		{
			if ((this._Message_Time != value))
			{
				this.OnMessage_TimeChanging(value);
				this.SendPropertyChanging();
				this._Message_Time = value;
				this.SendPropertyChanged("Message_Time");
				this.OnMessage_TimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PartyStatus")]
public partial class PartyStatus : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StudentNum;
	
	private string _MemberStatus_NO;
	
	private System.Nullable<System.DateTime> _AuditTime1;
	
	private string _Auditor1;
	
	private string _AuditOpinion1;
	
	private System.Nullable<System.DateTime> _AuditTime2;
	
	private string _Auditor2;
	
	private string _AuditOpinion2;
	
	private System.Nullable<System.DateTime> _AuditTime3;
	
	private string _Auditor3;
	
	private string _AuditOpinion3;
	
	private System.Nullable<int> _Student_Status;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStudentNumChanging(string value);
    partial void OnStudentNumChanged();
    partial void OnMemberStatus_NOChanging(string value);
    partial void OnMemberStatus_NOChanged();
    partial void OnAuditTime1Changing(System.Nullable<System.DateTime> value);
    partial void OnAuditTime1Changed();
    partial void OnAuditor1Changing(string value);
    partial void OnAuditor1Changed();
    partial void OnAuditOpinion1Changing(string value);
    partial void OnAuditOpinion1Changed();
    partial void OnAuditTime2Changing(System.Nullable<System.DateTime> value);
    partial void OnAuditTime2Changed();
    partial void OnAuditor2Changing(string value);
    partial void OnAuditor2Changed();
    partial void OnAuditOpinion2Changing(string value);
    partial void OnAuditOpinion2Changed();
    partial void OnAuditTime3Changing(System.Nullable<System.DateTime> value);
    partial void OnAuditTime3Changed();
    partial void OnAuditor3Changing(string value);
    partial void OnAuditor3Changed();
    partial void OnAuditOpinion3Changing(string value);
    partial void OnAuditOpinion3Changed();
    partial void OnStudent_StatusChanging(System.Nullable<int> value);
    partial void OnStudent_StatusChanged();
    #endregion
	
	public PartyStatus()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNum", DbType="VarChar(50)")]
	public string StudentNum
	{
		get
		{
			return this._StudentNum;
		}
		set
		{
			if ((this._StudentNum != value))
			{
				this.OnStudentNumChanging(value);
				this.SendPropertyChanging();
				this._StudentNum = value;
				this.SendPropertyChanged("StudentNum");
				this.OnStudentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberStatus_NO", DbType="VarChar(50)")]
	public string MemberStatus_NO
	{
		get
		{
			return this._MemberStatus_NO;
		}
		set
		{
			if ((this._MemberStatus_NO != value))
			{
				this.OnMemberStatus_NOChanging(value);
				this.SendPropertyChanging();
				this._MemberStatus_NO = value;
				this.SendPropertyChanged("MemberStatus_NO");
				this.OnMemberStatus_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditTime1", DbType="DateTime")]
	public System.Nullable<System.DateTime> AuditTime1
	{
		get
		{
			return this._AuditTime1;
		}
		set
		{
			if ((this._AuditTime1 != value))
			{
				this.OnAuditTime1Changing(value);
				this.SendPropertyChanging();
				this._AuditTime1 = value;
				this.SendPropertyChanged("AuditTime1");
				this.OnAuditTime1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auditor1", DbType="VarChar(50)")]
	public string Auditor1
	{
		get
		{
			return this._Auditor1;
		}
		set
		{
			if ((this._Auditor1 != value))
			{
				this.OnAuditor1Changing(value);
				this.SendPropertyChanging();
				this._Auditor1 = value;
				this.SendPropertyChanged("Auditor1");
				this.OnAuditor1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditOpinion1", DbType="VarChar(MAX)")]
	public string AuditOpinion1
	{
		get
		{
			return this._AuditOpinion1;
		}
		set
		{
			if ((this._AuditOpinion1 != value))
			{
				this.OnAuditOpinion1Changing(value);
				this.SendPropertyChanging();
				this._AuditOpinion1 = value;
				this.SendPropertyChanged("AuditOpinion1");
				this.OnAuditOpinion1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditTime2", DbType="DateTime")]
	public System.Nullable<System.DateTime> AuditTime2
	{
		get
		{
			return this._AuditTime2;
		}
		set
		{
			if ((this._AuditTime2 != value))
			{
				this.OnAuditTime2Changing(value);
				this.SendPropertyChanging();
				this._AuditTime2 = value;
				this.SendPropertyChanged("AuditTime2");
				this.OnAuditTime2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auditor2", DbType="VarChar(50)")]
	public string Auditor2
	{
		get
		{
			return this._Auditor2;
		}
		set
		{
			if ((this._Auditor2 != value))
			{
				this.OnAuditor2Changing(value);
				this.SendPropertyChanging();
				this._Auditor2 = value;
				this.SendPropertyChanged("Auditor2");
				this.OnAuditor2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditOpinion2", DbType="VarChar(MAX)")]
	public string AuditOpinion2
	{
		get
		{
			return this._AuditOpinion2;
		}
		set
		{
			if ((this._AuditOpinion2 != value))
			{
				this.OnAuditOpinion2Changing(value);
				this.SendPropertyChanging();
				this._AuditOpinion2 = value;
				this.SendPropertyChanged("AuditOpinion2");
				this.OnAuditOpinion2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditTime3", DbType="DateTime")]
	public System.Nullable<System.DateTime> AuditTime3
	{
		get
		{
			return this._AuditTime3;
		}
		set
		{
			if ((this._AuditTime3 != value))
			{
				this.OnAuditTime3Changing(value);
				this.SendPropertyChanging();
				this._AuditTime3 = value;
				this.SendPropertyChanged("AuditTime3");
				this.OnAuditTime3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auditor3", DbType="VarChar(50)")]
	public string Auditor3
	{
		get
		{
			return this._Auditor3;
		}
		set
		{
			if ((this._Auditor3 != value))
			{
				this.OnAuditor3Changing(value);
				this.SendPropertyChanging();
				this._Auditor3 = value;
				this.SendPropertyChanged("Auditor3");
				this.OnAuditor3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditOpinion3", DbType="VarChar(MAX)")]
	public string AuditOpinion3
	{
		get
		{
			return this._AuditOpinion3;
		}
		set
		{
			if ((this._AuditOpinion3 != value))
			{
				this.OnAuditOpinion3Changing(value);
				this.SendPropertyChanging();
				this._AuditOpinion3 = value;
				this.SendPropertyChanged("AuditOpinion3");
				this.OnAuditOpinion3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Status", DbType="Int")]
	public System.Nullable<int> Student_Status
	{
		get
		{
			return this._Student_Status;
		}
		set
		{
			if ((this._Student_Status != value))
			{
				this.OnStudent_StatusChanging(value);
				this.SendPropertyChanging();
				this._Student_Status = value;
				this.SendPropertyChanged("Student_Status");
				this.OnStudent_StatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Record_Details")]
public partial class Record_Details : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StudentNum;
	
	private System.Nullable<int> _Detail_Type;
	
	private string _Operator;
	
	private System.Nullable<System.DateTime> _Operate;
	
	private string _Details_Contents;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStudentNumChanging(string value);
    partial void OnStudentNumChanged();
    partial void OnDetail_TypeChanging(System.Nullable<int> value);
    partial void OnDetail_TypeChanged();
    partial void OnOperatorChanging(string value);
    partial void OnOperatorChanged();
    partial void OnOperateChanging(System.Nullable<System.DateTime> value);
    partial void OnOperateChanged();
    partial void OnDetails_ContentsChanging(string value);
    partial void OnDetails_ContentsChanged();
    #endregion
	
	public Record_Details()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNum", DbType="VarChar(50)")]
	public string StudentNum
	{
		get
		{
			return this._StudentNum;
		}
		set
		{
			if ((this._StudentNum != value))
			{
				this.OnStudentNumChanging(value);
				this.SendPropertyChanging();
				this._StudentNum = value;
				this.SendPropertyChanged("StudentNum");
				this.OnStudentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail_Type", DbType="Int")]
	public System.Nullable<int> Detail_Type
	{
		get
		{
			return this._Detail_Type;
		}
		set
		{
			if ((this._Detail_Type != value))
			{
				this.OnDetail_TypeChanging(value);
				this.SendPropertyChanging();
				this._Detail_Type = value;
				this.SendPropertyChanged("Detail_Type");
				this.OnDetail_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="VarChar(50)")]
	public string Operator
	{
		get
		{
			return this._Operator;
		}
		set
		{
			if ((this._Operator != value))
			{
				this.OnOperatorChanging(value);
				this.SendPropertyChanging();
				this._Operator = value;
				this.SendPropertyChanged("Operator");
				this.OnOperatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operate", DbType="DateTime")]
	public System.Nullable<System.DateTime> Operate
	{
		get
		{
			return this._Operate;
		}
		set
		{
			if ((this._Operate != value))
			{
				this.OnOperateChanging(value);
				this.SendPropertyChanging();
				this._Operate = value;
				this.SendPropertyChanged("Operate");
				this.OnOperateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details_Contents", DbType="VarChar(500)")]
	public string Details_Contents
	{
		get
		{
			return this._Details_Contents;
		}
		set
		{
			if ((this._Details_Contents != value))
			{
				this.OnDetails_ContentsChanging(value);
				this.SendPropertyChanging();
				this._Details_Contents = value;
				this.SendPropertyChanged("Details_Contents");
				this.OnDetails_ContentsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Update_Data")]
public partial class Update_Data : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Update1;
	
	private string _Update2;
	
	private string _Update3;
	
	private string _Update4;
	
	private string _Update5;
	
	private string _Update6;
	
	private string _Update7;
	
	private string _Update8;
	
	private string _Update9;
	
	private string _Update10;
	
	private int _Update_Status;
	
	private System.Nullable<int> _Update_Type;
	
	private System.Nullable<System.DateTime> _Update_Time;
	
	private System.Nullable<System.DateTime> _Review_Time;
	
	private string _Update_Theme;
	
	private string _Update_Reason;
	
	private string _Update_Remark;
	
	private string _Audit_Person;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUpdate1Changing(string value);
    partial void OnUpdate1Changed();
    partial void OnUpdate2Changing(string value);
    partial void OnUpdate2Changed();
    partial void OnUpdate3Changing(string value);
    partial void OnUpdate3Changed();
    partial void OnUpdate4Changing(string value);
    partial void OnUpdate4Changed();
    partial void OnUpdate5Changing(string value);
    partial void OnUpdate5Changed();
    partial void OnUpdate6Changing(string value);
    partial void OnUpdate6Changed();
    partial void OnUpdate7Changing(string value);
    partial void OnUpdate7Changed();
    partial void OnUpdate8Changing(string value);
    partial void OnUpdate8Changed();
    partial void OnUpdate9Changing(string value);
    partial void OnUpdate9Changed();
    partial void OnUpdate10Changing(string value);
    partial void OnUpdate10Changed();
    partial void OnUpdate_StatusChanging(int value);
    partial void OnUpdate_StatusChanged();
    partial void OnUpdate_TypeChanging(System.Nullable<int> value);
    partial void OnUpdate_TypeChanged();
    partial void OnUpdate_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_TimeChanged();
    partial void OnReview_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnReview_TimeChanged();
    partial void OnUpdate_ThemeChanging(string value);
    partial void OnUpdate_ThemeChanged();
    partial void OnUpdate_ReasonChanging(string value);
    partial void OnUpdate_ReasonChanged();
    partial void OnUpdate_RemarkChanging(string value);
    partial void OnUpdate_RemarkChanged();
    partial void OnAudit_PersonChanging(string value);
    partial void OnAudit_PersonChanged();
    #endregion
	
	public Update_Data()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update1", DbType="VarChar(MAX)")]
	public string Update1
	{
		get
		{
			return this._Update1;
		}
		set
		{
			if ((this._Update1 != value))
			{
				this.OnUpdate1Changing(value);
				this.SendPropertyChanging();
				this._Update1 = value;
				this.SendPropertyChanged("Update1");
				this.OnUpdate1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update2", DbType="VarChar(MAX)")]
	public string Update2
	{
		get
		{
			return this._Update2;
		}
		set
		{
			if ((this._Update2 != value))
			{
				this.OnUpdate2Changing(value);
				this.SendPropertyChanging();
				this._Update2 = value;
				this.SendPropertyChanged("Update2");
				this.OnUpdate2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update3", DbType="VarChar(MAX)")]
	public string Update3
	{
		get
		{
			return this._Update3;
		}
		set
		{
			if ((this._Update3 != value))
			{
				this.OnUpdate3Changing(value);
				this.SendPropertyChanging();
				this._Update3 = value;
				this.SendPropertyChanged("Update3");
				this.OnUpdate3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update4", DbType="VarChar(MAX)")]
	public string Update4
	{
		get
		{
			return this._Update4;
		}
		set
		{
			if ((this._Update4 != value))
			{
				this.OnUpdate4Changing(value);
				this.SendPropertyChanging();
				this._Update4 = value;
				this.SendPropertyChanged("Update4");
				this.OnUpdate4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update5", DbType="VarChar(MAX)")]
	public string Update5
	{
		get
		{
			return this._Update5;
		}
		set
		{
			if ((this._Update5 != value))
			{
				this.OnUpdate5Changing(value);
				this.SendPropertyChanging();
				this._Update5 = value;
				this.SendPropertyChanged("Update5");
				this.OnUpdate5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update6", DbType="VarChar(MAX)")]
	public string Update6
	{
		get
		{
			return this._Update6;
		}
		set
		{
			if ((this._Update6 != value))
			{
				this.OnUpdate6Changing(value);
				this.SendPropertyChanging();
				this._Update6 = value;
				this.SendPropertyChanged("Update6");
				this.OnUpdate6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update7", DbType="VarChar(MAX)")]
	public string Update7
	{
		get
		{
			return this._Update7;
		}
		set
		{
			if ((this._Update7 != value))
			{
				this.OnUpdate7Changing(value);
				this.SendPropertyChanging();
				this._Update7 = value;
				this.SendPropertyChanged("Update7");
				this.OnUpdate7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update8", DbType="VarChar(MAX)")]
	public string Update8
	{
		get
		{
			return this._Update8;
		}
		set
		{
			if ((this._Update8 != value))
			{
				this.OnUpdate8Changing(value);
				this.SendPropertyChanging();
				this._Update8 = value;
				this.SendPropertyChanged("Update8");
				this.OnUpdate8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update9", DbType="VarChar(MAX)")]
	public string Update9
	{
		get
		{
			return this._Update9;
		}
		set
		{
			if ((this._Update9 != value))
			{
				this.OnUpdate9Changing(value);
				this.SendPropertyChanging();
				this._Update9 = value;
				this.SendPropertyChanged("Update9");
				this.OnUpdate9Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update10", DbType="VarChar(MAX)")]
	public string Update10
	{
		get
		{
			return this._Update10;
		}
		set
		{
			if ((this._Update10 != value))
			{
				this.OnUpdate10Changing(value);
				this.SendPropertyChanging();
				this._Update10 = value;
				this.SendPropertyChanged("Update10");
				this.OnUpdate10Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Status", DbType="Int NOT NULL")]
	public int Update_Status
	{
		get
		{
			return this._Update_Status;
		}
		set
		{
			if ((this._Update_Status != value))
			{
				this.OnUpdate_StatusChanging(value);
				this.SendPropertyChanging();
				this._Update_Status = value;
				this.SendPropertyChanged("Update_Status");
				this.OnUpdate_StatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Type", DbType="Int")]
	public System.Nullable<int> Update_Type
	{
		get
		{
			return this._Update_Type;
		}
		set
		{
			if ((this._Update_Type != value))
			{
				this.OnUpdate_TypeChanging(value);
				this.SendPropertyChanging();
				this._Update_Type = value;
				this.SendPropertyChanged("Update_Type");
				this.OnUpdate_TypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Update_Time
	{
		get
		{
			return this._Update_Time;
		}
		set
		{
			if ((this._Update_Time != value))
			{
				this.OnUpdate_TimeChanging(value);
				this.SendPropertyChanging();
				this._Update_Time = value;
				this.SendPropertyChanged("Update_Time");
				this.OnUpdate_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Review_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Review_Time
	{
		get
		{
			return this._Review_Time;
		}
		set
		{
			if ((this._Review_Time != value))
			{
				this.OnReview_TimeChanging(value);
				this.SendPropertyChanging();
				this._Review_Time = value;
				this.SendPropertyChanged("Review_Time");
				this.OnReview_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Theme", DbType="VarChar(100)")]
	public string Update_Theme
	{
		get
		{
			return this._Update_Theme;
		}
		set
		{
			if ((this._Update_Theme != value))
			{
				this.OnUpdate_ThemeChanging(value);
				this.SendPropertyChanging();
				this._Update_Theme = value;
				this.SendPropertyChanged("Update_Theme");
				this.OnUpdate_ThemeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Reason", DbType="VarChar(200)")]
	public string Update_Reason
	{
		get
		{
			return this._Update_Reason;
		}
		set
		{
			if ((this._Update_Reason != value))
			{
				this.OnUpdate_ReasonChanging(value);
				this.SendPropertyChanging();
				this._Update_Reason = value;
				this.SendPropertyChanged("Update_Reason");
				this.OnUpdate_ReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_Remark", DbType="VarChar(200)")]
	public string Update_Remark
	{
		get
		{
			return this._Update_Remark;
		}
		set
		{
			if ((this._Update_Remark != value))
			{
				this.OnUpdate_RemarkChanging(value);
				this.SendPropertyChanging();
				this._Update_Remark = value;
				this.SendPropertyChanged("Update_Remark");
				this.OnUpdate_RemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audit_Person", DbType="VarChar(10)")]
	public string Audit_Person
	{
		get
		{
			return this._Audit_Person;
		}
		set
		{
			if ((this._Audit_Person != value))
			{
				this.OnAudit_PersonChanging(value);
				this.SendPropertyChanging();
				this._Audit_Person = value;
				this.SendPropertyChanged("Audit_Person");
				this.OnAudit_PersonChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Work_Info")]
public partial class Work_Info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Work_Message_Id;
	
	private string _Power;
	
	private System.Nullable<System.DateTime> _Work_Message_Time;
	
	private string _Work_Content;
	
	private string _Promulgator;
	
	private System.Nullable<System.DateTime> _Created_on_time;
	
	private System.Nullable<System.DateTime> _Update_time;
	
	private string _Metting_Theme;
	
	private System.Nullable<int> _Metting_Status;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWork_Message_IdChanging(int value);
    partial void OnWork_Message_IdChanged();
    partial void OnPowerChanging(string value);
    partial void OnPowerChanged();
    partial void OnWork_Message_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnWork_Message_TimeChanged();
    partial void OnWork_ContentChanging(string value);
    partial void OnWork_ContentChanged();
    partial void OnPromulgatorChanging(string value);
    partial void OnPromulgatorChanged();
    partial void OnCreated_on_timeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_on_timeChanged();
    partial void OnUpdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_timeChanged();
    partial void OnMetting_ThemeChanging(string value);
    partial void OnMetting_ThemeChanged();
    partial void OnMetting_StatusChanging(System.Nullable<int> value);
    partial void OnMetting_StatusChanged();
    #endregion
	
	public Work_Info()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_Message_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Work_Message_Id
	{
		get
		{
			return this._Work_Message_Id;
		}
		set
		{
			if ((this._Work_Message_Id != value))
			{
				this.OnWork_Message_IdChanging(value);
				this.SendPropertyChanging();
				this._Work_Message_Id = value;
				this.SendPropertyChanged("Work_Message_Id");
				this.OnWork_Message_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="VarChar(50)")]
	public string Power
	{
		get
		{
			return this._Power;
		}
		set
		{
			if ((this._Power != value))
			{
				this.OnPowerChanging(value);
				this.SendPropertyChanging();
				this._Power = value;
				this.SendPropertyChanged("Power");
				this.OnPowerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_Message_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Work_Message_Time
	{
		get
		{
			return this._Work_Message_Time;
		}
		set
		{
			if ((this._Work_Message_Time != value))
			{
				this.OnWork_Message_TimeChanging(value);
				this.SendPropertyChanging();
				this._Work_Message_Time = value;
				this.SendPropertyChanged("Work_Message_Time");
				this.OnWork_Message_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_Content", DbType="VarChar(MAX)")]
	public string Work_Content
	{
		get
		{
			return this._Work_Content;
		}
		set
		{
			if ((this._Work_Content != value))
			{
				this.OnWork_ContentChanging(value);
				this.SendPropertyChanging();
				this._Work_Content = value;
				this.SendPropertyChanged("Work_Content");
				this.OnWork_ContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promulgator", DbType="VarChar(50)")]
	public string Promulgator
	{
		get
		{
			return this._Promulgator;
		}
		set
		{
			if ((this._Promulgator != value))
			{
				this.OnPromulgatorChanging(value);
				this.SendPropertyChanging();
				this._Promulgator = value;
				this.SendPropertyChanged("Promulgator");
				this.OnPromulgatorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_on_time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Created_on_time
	{
		get
		{
			return this._Created_on_time;
		}
		set
		{
			if ((this._Created_on_time != value))
			{
				this.OnCreated_on_timeChanging(value);
				this.SendPropertyChanging();
				this._Created_on_time = value;
				this.SendPropertyChanged("Created_on_time");
				this.OnCreated_on_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Update_time
	{
		get
		{
			return this._Update_time;
		}
		set
		{
			if ((this._Update_time != value))
			{
				this.OnUpdate_timeChanging(value);
				this.SendPropertyChanging();
				this._Update_time = value;
				this.SendPropertyChanged("Update_time");
				this.OnUpdate_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metting_Theme", DbType="VarChar(100)")]
	public string Metting_Theme
	{
		get
		{
			return this._Metting_Theme;
		}
		set
		{
			if ((this._Metting_Theme != value))
			{
				this.OnMetting_ThemeChanging(value);
				this.SendPropertyChanging();
				this._Metting_Theme = value;
				this.SendPropertyChanged("Metting_Theme");
				this.OnMetting_ThemeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metting_Status", DbType="Int")]
	public System.Nullable<int> Metting_Status
	{
		get
		{
			return this._Metting_Status;
		}
		set
		{
			if ((this._Metting_Status != value))
			{
				this.OnMetting_StatusChanging(value);
				this.SendPropertyChanging();
				this._Metting_Status = value;
				this.SendPropertyChanged("Metting_Status");
				this.OnMetting_StatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PartyData")]
public partial class PartyData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StudentNum;
	
	private string _Name;
	
	private string _Password;
	
	private string _Sex;
	
	private string _Photo;
	
	private string _Birth;
	
	private string _PlaceOfOrigin;
	
	private string _Telephone;
	
	private string _Address;
	
	private System.Nullable<int> _ClassNO;
	
	private System.Nullable<int> _CollegeNO;
	
	private System.Nullable<System.DateTime> _StartTime;
	
	private System.Nullable<System.DateTime> _EndTime;
	
	private System.Nullable<int> _PartyDues;
	
	private string _FromPlace;
	
	private string _RemovePlace;
	
	private string _Power_NO;
	
	private string _Files;
	
	private string _File_Clerk;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStudentNumChanging(string value);
    partial void OnStudentNumChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnBirthChanging(string value);
    partial void OnBirthChanged();
    partial void OnPlaceOfOriginChanging(string value);
    partial void OnPlaceOfOriginChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnClassNOChanging(System.Nullable<int> value);
    partial void OnClassNOChanged();
    partial void OnCollegeNOChanging(System.Nullable<int> value);
    partial void OnCollegeNOChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnPartyDuesChanging(System.Nullable<int> value);
    partial void OnPartyDuesChanged();
    partial void OnFromPlaceChanging(string value);
    partial void OnFromPlaceChanged();
    partial void OnRemovePlaceChanging(string value);
    partial void OnRemovePlaceChanged();
    partial void OnPower_NOChanging(string value);
    partial void OnPower_NOChanged();
    partial void OnFilesChanging(string value);
    partial void OnFilesChanged();
    partial void OnFile_ClerkChanging(string value);
    partial void OnFile_ClerkChanged();
    #endregion
	
	public PartyData()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNum", DbType="VarChar(50)")]
	public string StudentNum
	{
		get
		{
			return this._StudentNum;
		}
		set
		{
			if ((this._StudentNum != value))
			{
				this.OnStudentNumChanging(value);
				this.SendPropertyChanging();
				this._StudentNum = value;
				this.SendPropertyChanged("StudentNum");
				this.OnStudentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NChar(4)")]
	public string Sex
	{
		get
		{
			return this._Sex;
		}
		set
		{
			if ((this._Sex != value))
			{
				this.OnSexChanging(value);
				this.SendPropertyChanging();
				this._Sex = value;
				this.SendPropertyChanged("Sex");
				this.OnSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarChar(200)")]
	public string Photo
	{
		get
		{
			return this._Photo;
		}
		set
		{
			if ((this._Photo != value))
			{
				this.OnPhotoChanging(value);
				this.SendPropertyChanging();
				this._Photo = value;
				this.SendPropertyChanged("Photo");
				this.OnPhotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birth", DbType="VarChar(20)")]
	public string Birth
	{
		get
		{
			return this._Birth;
		}
		set
		{
			if ((this._Birth != value))
			{
				this.OnBirthChanging(value);
				this.SendPropertyChanging();
				this._Birth = value;
				this.SendPropertyChanged("Birth");
				this.OnBirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfOrigin", DbType="VarChar(50)")]
	public string PlaceOfOrigin
	{
		get
		{
			return this._PlaceOfOrigin;
		}
		set
		{
			if ((this._PlaceOfOrigin != value))
			{
				this.OnPlaceOfOriginChanging(value);
				this.SendPropertyChanging();
				this._PlaceOfOrigin = value;
				this.SendPropertyChanged("PlaceOfOrigin");
				this.OnPlaceOfOriginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(50)")]
	public string Telephone
	{
		get
		{
			return this._Telephone;
		}
		set
		{
			if ((this._Telephone != value))
			{
				this.OnTelephoneChanging(value);
				this.SendPropertyChanging();
				this._Telephone = value;
				this.SendPropertyChanged("Telephone");
				this.OnTelephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassNO", DbType="Int")]
	public System.Nullable<int> ClassNO
	{
		get
		{
			return this._ClassNO;
		}
		set
		{
			if ((this._ClassNO != value))
			{
				this.OnClassNOChanging(value);
				this.SendPropertyChanging();
				this._ClassNO = value;
				this.SendPropertyChanged("ClassNO");
				this.OnClassNOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeNO", DbType="Int")]
	public System.Nullable<int> CollegeNO
	{
		get
		{
			return this._CollegeNO;
		}
		set
		{
			if ((this._CollegeNO != value))
			{
				this.OnCollegeNOChanging(value);
				this.SendPropertyChanging();
				this._CollegeNO = value;
				this.SendPropertyChanged("CollegeNO");
				this.OnCollegeNOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> StartTime
	{
		get
		{
			return this._StartTime;
		}
		set
		{
			if ((this._StartTime != value))
			{
				this.OnStartTimeChanging(value);
				this.SendPropertyChanging();
				this._StartTime = value;
				this.SendPropertyChanged("StartTime");
				this.OnStartTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> EndTime
	{
		get
		{
			return this._EndTime;
		}
		set
		{
			if ((this._EndTime != value))
			{
				this.OnEndTimeChanging(value);
				this.SendPropertyChanging();
				this._EndTime = value;
				this.SendPropertyChanged("EndTime");
				this.OnEndTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyDues", DbType="Int")]
	public System.Nullable<int> PartyDues
	{
		get
		{
			return this._PartyDues;
		}
		set
		{
			if ((this._PartyDues != value))
			{
				this.OnPartyDuesChanging(value);
				this.SendPropertyChanging();
				this._PartyDues = value;
				this.SendPropertyChanged("PartyDues");
				this.OnPartyDuesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromPlace", DbType="VarChar(50)")]
	public string FromPlace
	{
		get
		{
			return this._FromPlace;
		}
		set
		{
			if ((this._FromPlace != value))
			{
				this.OnFromPlaceChanging(value);
				this.SendPropertyChanging();
				this._FromPlace = value;
				this.SendPropertyChanged("FromPlace");
				this.OnFromPlaceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemovePlace", DbType="VarChar(50)")]
	public string RemovePlace
	{
		get
		{
			return this._RemovePlace;
		}
		set
		{
			if ((this._RemovePlace != value))
			{
				this.OnRemovePlaceChanging(value);
				this.SendPropertyChanging();
				this._RemovePlace = value;
				this.SendPropertyChanged("RemovePlace");
				this.OnRemovePlaceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power_NO", DbType="VarChar(50)")]
	public string Power_NO
	{
		get
		{
			return this._Power_NO;
		}
		set
		{
			if ((this._Power_NO != value))
			{
				this.OnPower_NOChanging(value);
				this.SendPropertyChanging();
				this._Power_NO = value;
				this.SendPropertyChanged("Power_NO");
				this.OnPower_NOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Files", DbType="VarChar(300)")]
	public string Files
	{
		get
		{
			return this._Files;
		}
		set
		{
			if ((this._Files != value))
			{
				this.OnFilesChanging(value);
				this.SendPropertyChanging();
				this._Files = value;
				this.SendPropertyChanged("Files");
				this.OnFilesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_File_Clerk", DbType="VarChar(50)")]
	public string File_Clerk
	{
		get
		{
			return this._File_Clerk;
		}
		set
		{
			if ((this._File_Clerk != value))
			{
				this.OnFile_ClerkChanging(value);
				this.SendPropertyChanging();
				this._File_Clerk = value;
				this.SendPropertyChanged("File_Clerk");
				this.OnFile_ClerkChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Datum")]
public partial class Datum : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Datum_ID;
	
	private string _StudentNum;
	
	private string _Datum_URL;
	
	private int _Audit_State;
	
	private System.Nullable<System.DateTime> _Upload_Time;
	
	private string _Browse_Authority;
	
	private string _Datum_Name;
	
	private System.Nullable<int> _Download_Num;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDatum_IDChanging(int value);
    partial void OnDatum_IDChanged();
    partial void OnStudentNumChanging(string value);
    partial void OnStudentNumChanged();
    partial void OnDatum_URLChanging(string value);
    partial void OnDatum_URLChanged();
    partial void OnAudit_StateChanging(int value);
    partial void OnAudit_StateChanged();
    partial void OnUpload_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpload_TimeChanged();
    partial void OnBrowse_AuthorityChanging(string value);
    partial void OnBrowse_AuthorityChanged();
    partial void OnDatum_NameChanging(string value);
    partial void OnDatum_NameChanged();
    partial void OnDownload_NumChanging(System.Nullable<int> value);
    partial void OnDownload_NumChanged();
    #endregion
	
	public Datum()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Datum_ID
	{
		get
		{
			return this._Datum_ID;
		}
		set
		{
			if ((this._Datum_ID != value))
			{
				this.OnDatum_IDChanging(value);
				this.SendPropertyChanging();
				this._Datum_ID = value;
				this.SendPropertyChanged("Datum_ID");
				this.OnDatum_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNum", DbType="VarChar(50)")]
	public string StudentNum
	{
		get
		{
			return this._StudentNum;
		}
		set
		{
			if ((this._StudentNum != value))
			{
				this.OnStudentNumChanging(value);
				this.SendPropertyChanging();
				this._StudentNum = value;
				this.SendPropertyChanged("StudentNum");
				this.OnStudentNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum_URL", DbType="VarChar(200)")]
	public string Datum_URL
	{
		get
		{
			return this._Datum_URL;
		}
		set
		{
			if ((this._Datum_URL != value))
			{
				this.OnDatum_URLChanging(value);
				this.SendPropertyChanging();
				this._Datum_URL = value;
				this.SendPropertyChanged("Datum_URL");
				this.OnDatum_URLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audit_State", DbType="Int NOT NULL")]
	public int Audit_State
	{
		get
		{
			return this._Audit_State;
		}
		set
		{
			if ((this._Audit_State != value))
			{
				this.OnAudit_StateChanging(value);
				this.SendPropertyChanging();
				this._Audit_State = value;
				this.SendPropertyChanged("Audit_State");
				this.OnAudit_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Upload_Time", DbType="DateTime")]
	public System.Nullable<System.DateTime> Upload_Time
	{
		get
		{
			return this._Upload_Time;
		}
		set
		{
			if ((this._Upload_Time != value))
			{
				this.OnUpload_TimeChanging(value);
				this.SendPropertyChanging();
				this._Upload_Time = value;
				this.SendPropertyChanged("Upload_Time");
				this.OnUpload_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Browse_Authority", DbType="VarChar(200)")]
	public string Browse_Authority
	{
		get
		{
			return this._Browse_Authority;
		}
		set
		{
			if ((this._Browse_Authority != value))
			{
				this.OnBrowse_AuthorityChanging(value);
				this.SendPropertyChanging();
				this._Browse_Authority = value;
				this.SendPropertyChanged("Browse_Authority");
				this.OnBrowse_AuthorityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum_Name", DbType="VarChar(100)")]
	public string Datum_Name
	{
		get
		{
			return this._Datum_Name;
		}
		set
		{
			if ((this._Datum_Name != value))
			{
				this.OnDatum_NameChanging(value);
				this.SendPropertyChanging();
				this._Datum_Name = value;
				this.SendPropertyChanged("Datum_Name");
				this.OnDatum_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Download_Num", DbType="Int")]
	public System.Nullable<int> Download_Num
	{
		get
		{
			return this._Download_Num;
		}
		set
		{
			if ((this._Download_Num != value))
			{
				this.OnDownload_NumChanging(value);
				this.SendPropertyChanging();
				this._Download_Num = value;
				this.SendPropertyChanged("Download_Num");
				this.OnDownload_NumChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
